### ISSUE TITLE
TODO list back

### ISSUE THREAD

**Issue by aflatoune** [aflatoune/consotracker#1]
- [x] test that ROUE gives same results with `forecast_window` and `n_steps`
- [x] add metrics (MAE, RMSE, MDA)
- [ ] use Insee API rather than DBnomics
- [x] handle NA during processing (pct_change and yoy)
- [x] add `dataset_code` arg for dbnomics series download
